FROM python:3.6.9-buster
MAINTAINER Andrea Ferretti

ENV APP_ROOT=/opt/charade
WORKDIR ${APP_ROOT}

RUN apt-get update
RUN apt-get -y install python-pip
RUN pip install pipenv

ENV PIP_DEFAULT_TIMEOUT=6000
ENV PIPENV_TIMEOUT=6000
COPY Pipfile Pipfile
RUN pipenv lock --verbose